version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '02:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      dependencies:
        dependency-type: production
        exclude-patterns:
          - 'puppeteer*'
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - 'puppeteer*'
        patterns:
          - '*'
      puppeteer:
        patterns:
          - 'puppeteer*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '04:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - '*'

enable-beta-ecosystems: true
security-updates-only: true
