name: Tests

on: []

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v6

      - name: ðŸ§° Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: ðŸ“¦ Install dependencies
        run: bun ci

      - name: ðŸ§ª Run all tests
        run: bun test:all
        env:
          PUPPETEER_EXECUTABLE_PATH: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
